
const AdvisersCommissionTableConfig = {
    columnsData: [
        { id: "PayrollMonth", label: "Payroll Month", minWidth: 150 },
        { id: "InvoiceReference", label: "Invoice Reference", minWidth: 150 },
        { id: "PolicyNo", label: "Policy No", minWidth: 150 },
        { id: "Adviser", label: "Adviser", minWidth: 150 },
        { id: "SecondaryAdviser", label: "Secondary Adviser", minWidth: 150 },
        { id: "BDM", label: "BDM", minWidth: 150 },
        { id: "FirstPolicyHolder", label: "First Policy Holder", minWidth: 150 },
        { id: "SecondPolicyHolder", label: "Second Policy Holder", minWidth: 150 },
        { id: "Provider", label: "Provider", minWidth: 150 },
        { id: "Product", label: "Product", minWidth: 150 },
        { id: "PolicyCurrency", label: "Policy Currency", minWidth: 150 },
        { id: "TransactionDate", label: "Transaction Date", minWidth: 150 },
        { id: "PremiumFrequency", label: "Premium Frequency", minWidth: 150 },
        { id: "EarnedCurrency", label: "Earned Currency", minWidth: 150 },
        { id: "EarnedAmount", label: "Earned Amount", minWidth: 150 },
        { id: "FXRate", label: "FX Rate", minWidth: 150 },
        { id: "PaymentCurrency", label: "Payment Currency", minWidth: 150 },
        { id: "PaymentAmount", label: "Payment Amount", minWidth: 150 },
        { id: "GSTRate", label: "GST Rate", minWidth: 150 },
        { id: "GSTAmount", label: "GST Amount", minWidth: 150 },
        { id: "PaymentNetGST", label: "Payment Net GST", minWidth: 150 },
        { id: "BandingType", label: "Banding Type", minWidth: 150 },
        { id: "AdviserBanding", label: "Adviser Banding", minWidth: 150 },
        { id: "NetCommission", label: "Net Commission", minWidth: 150 },
        { id: "ClawbackPot", label: "Clawback Pot", minWidth: 150 },
        { id: "ClawbackAmount", label: "Clawback Amount", minWidth: 150 },
        { id: "BDMCommission", label: "BDM Commission", minWidth: 150 },
        { id: "BDMCommissionAmount", label: "BDM Commission Amount", minWidth: 150 },
        { id: "AdviserAmountPayable", label: "Adviser Amount Payable", minWidth: 150 },
        { id: "ProductType", label: "Product Type", minWidth: 150 },
        { id: "CommissionType", label: "Commission Type", minWidth: 150 },
    ],
  };
  
  export default AdvisersCommissionTableConfig;
