const RowDataAdmin = {
  rowData: [
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV123456",
      PolicyNo: "POL987654",
      Adviser: "John Smith",
      SecondaryAdviser: "Adviser B",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jane Doe",
      SecondPolicyHolder: "John Doe",
      Provider: "Utmost International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/5/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV1234",
      PolicyNo: "POL987656",
      Adviser: "Jamie Oliver",
      SecondaryAdviser: "Adviser C",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jonah Smith",
      SecondPolicyHolder: "John Doe",
      Provider: "All International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/6/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV1234",
      PolicyNo: "POL987656",
      Adviser: "Branda Smith",
      SecondaryAdviser: "Adviser C",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jonah Smith",
      SecondPolicyHolder: "John Doe",
      Provider: "All International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/6/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV1234",
      PolicyNo: "POL987656",
      Adviser: "John Smith",
      SecondaryAdviser: "Adviser C",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jonah Smith",
      SecondPolicyHolder: "John Doe",
      Provider: "All International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/6/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV1234",
      PolicyNo: "POL987656",
      Adviser: "John Smith",
      SecondaryAdviser: "Adviser C",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jonah Smith",
      SecondPolicyHolder: "John Doe",
      Provider: "All International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/6/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV1234",
      PolicyNo: "POL987656",
      Adviser: "Kgomotso Dungeni",
      SecondaryAdviser: "Adviser C",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jonah Smith",
      SecondPolicyHolder: "John Doe",
      Provider: "All International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/6/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
    {
      PayrollMonth: "June 2024",
      InvoiceReference: "INV1234",
      PolicyNo: "POL987656",
      Adviser: "John Smith",
      SecondaryAdviser: "Adviser C",
      BDM: "Joe Bloggs",
      FirstPolicyHolder: "Jonah Smith",
      SecondPolicyHolder: "John Doe",
      Provider: "All International",
      Product: "EIA",
      PolicyCurrency: "SGD",
      TransactionDate: "29/6/2024",
      PremiumFrequency: "Single",
      EarnedCurrency: "SGD",
      EarnedAmount: 7000,
      FXRate: "1.000000",
      PaymentCurrency: "SGD",
      PaymentAmount: 7000,
      GSTRate: "9%",
      GSTAmount: 577.98,
      PaymentNetGST: 6942.02,
      BandingType: "Standard",
      AdviserBanding: "80%",
      NetCommission: 5553.62,
      ClawbackPot: "0%",
      ClawbackAmount: 0.0,
      BDMCommission: "18%",
      BDMCommissionAmount: 1260,
      AdviserAmountPayable: 4293.62,
      ProductType: "Single Premium",
      CommissionType: "Non-Indemnified",
    },
  ],
};

export default RowDataAdmin;
