const TableConfig = {
  columnsData: [
    { id: "PayrollMonth", label: "Payroll Month", minWidth: 170 },
    { id: "InvoiceReference", label: "Invoice Refernce", minWidth: 170 },
    { id: "PolicyNo", label: "Policy No.", minWidth: 170 },
    { id: "Adviser", label: "Adviser", minWidth: 170 },
    { id: "SecondaryAdviser", label: "Secondary Adviser", minWidth: 170 },
    { id: "BDM", label: "BDM", minWidth: 100 },
    { id: "FirstPolicyHolder", label: "First Policy Holder", minWidth: 170 },
    { id: "SecondPolicyHolder", label: "Second Policy Holder", minWidth: 170 },
    { id: "Provider", label: "Provider", minWidth: 170 },
    { id: "Product", label: "Product", minWidth: 170 },
    { id: "PolicyCurrency", label: "Policy Currency", minWidth: 170 },
    { id: "TransactionDate", label: "Transaction Date", minWidth: 170 },
    { id: "PremiumFrequency", label: "Premium Frequency", minWidth: 170 },
    { id: "EarnedCurrency", label: "Earned Currency", minWidth: 170 },
    { id: "EarnedAmount", label: "Earned Amount", minWidth: 170 },
    { id: "FXRate", label: "FX Rate", minWidth: 170 },
    { id: "PaymentCurrency", label: "Payment Currency", minWidth: 170 },
    { id: "PaymentAmount", label: "Payment Amount", minWidth: 170 },
    { id: "GSTRate", label: "GST Rate", minWidth: 170 },
    { id: "GSTAmount", label: "GST Amount", minWidth: 170 },
    { id: "PaymentNetGST", label: "Payment Net GST", minWidth: 170 },
    { id: "BandingType", label: "Banding Type", minWidth: 170 },
    { id: "AdviserBanding", label: "Adviser Banding", minWidth: 170 },
    { id: "NetCommission", label: "NetCommission", minWidth: 170 },
    { id: "ClawbackPot", label: "Clawback Pot", minWidth: 170 },
    { id: "ClawbackAmount", label: "Clawback Amount", minWidth: 170 },
    { id: "BDMCommission", label: "BDM Commission", minWidth: 170 },
    {
      id: "BDMCommissionAmount",
      label: "BDM Commission Amount",
      minWidth: 170,
    },
    {
      id: "AdviserAmountPayable",
      label: "Adviser Amount Payable",
      minWidth: 170,
    },
    { id: "ProductType", label: "Product Type", minWidth: 170 },
    { id: "CommissionType", label: "Commission Type", minWidth: 170 },
  ],
};

export default TableConfig;
