name: Terraform Linting

on:
  pull_request: # Trigger on pull request events

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run linters
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: v1.58

  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.3.x # Adjust if needed

  #     - name: Run the Action
  #       uses: devops-infra/action-tflint@v0.3
  #       with:
  #         dir_filter: "*"
