name: Terraform Linting

on:
  pull_request: # Trigger on pull request events

jobs:
  tflint-checks:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Check out Git Repository
        uses: actions/checkout@v3

      # TFLint - Terraform Check
      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

      # Print TFLint version
      - name: Show version
        run: tflint --version

      # Install plugins
      - name: Init TFLint
        run: tflint --init

      # Run tflint command in each directory recursively
      - name: Run TFLint
        run: tflint -f compact --recursive

  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.3.x # Adjust if needed

  #     - name: Run the Action
  #       uses: devops-infra/action-tflint@v0.3
  #       with:
  #         dir_filter: "*"
